// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    HBtn: typeof import('./src/components/HBtn.vue')['default']
    HBtnGroup: typeof import('./src/components/HBtnGroup.vue')['default']
    HSlider: typeof import('./src/components/HSlider.vue')['default']
    HSpacer: typeof import('./src/components/HSpacer.vue')['default']
    SquareBtn: typeof import('./src/components/SquareBtn.vue')['default']
    TitleCard: typeof import('./src/components/TitleCard.vue')['default']
    Column: typeof import('./src/components/Main/Column.vue')['default']
    Keyboard: typeof import('./src/components/Main/Keyboard.vue')['default']
    NavBar: typeof import('./src/components/Main/NavBar.vue')['default']
    PianoKey: typeof import('./src/components/Main/PianoKey.vue')['default']
    FourierVisualizer: typeof import('./src/components/Main/FlexZone/FourierVisualizer.vue')['default']
    Spectrum: typeof import('./src/components/Main/FlexZone/Spectrum.vue')['default']
    Visuals: typeof import('./src/components/Main/FlexZone/Visuals.vue')['default']
    Waveform: typeof import('./src/components/Main/FlexZone/Waveform.vue')['default']
    Footer: typeof import('./src/components/Main/Footer/Footer.vue')['default']
    NewOscillator: typeof import('./src/components/Main/Oscillators/NewOscillator.vue')['default']
    Oscillator: typeof import('./src/components/Main/Oscillators/Oscillator.vue')['default']
    Oscillators: typeof import('./src/components/Main/Oscillators/Oscillators.vue')['default']
  }
}

export { }
