// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    HBtn: typeof import('./src/components/HBtn.vue')['default']
    HBtnGroup: typeof import('./src/components/HBtnGroup.vue')['default']
    HSlider: typeof import('./src/components/HSlider.vue')['default']
    HSpacer: typeof import('./src/components/HSpacer.vue')['default']
    FourierTransform: typeof import('./src/components/Main/FourierTransform.vue')['default']
    Keyboard: typeof import('./src/components/Main/Keyboard.vue')['default']
    NavBar: typeof import('./src/components/Main/NavBar.vue')['default']
    Oscillator: typeof import('./src/components/Main/Oscillator.vue')['default']
    PianoKey: typeof import('./src/components/Main/PianoKey.vue')['default']
    SynthDisplay: typeof import('./src/components/Main/SynthDisplay.vue')['default']
  }
}

export { }
