// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    HBtn: typeof import('./src/components/HBtn.vue')['default']
    HBtnGroup: typeof import('./src/components/HBtnGroup.vue')['default']
    HSlider: typeof import('./src/components/HSlider.vue')['default']
    HSpacer: typeof import('./src/components/HSpacer.vue')['default']
  }
}

export { }
